### ISSUE TITLE
[US39] Visualizar página principal 

### ISSUE THREAD

**Issue by LGomees** [desenho-2019/WebAPP#4]
## Descrição

Eu, como usuário/visitante, desejo visualizar a página principal para poder começar a utilizar as funcionalidades do site.

## Tipo

- História de usuário

## Critérios de aceitação

- [x] Deve conter a navbar principal da aplicação com botões de login, cadastro e anúncio.
- [x] Deve conter um campo para inserção da localização

**Comment by VictorRodriguesS0** [comment]
@LGomees acredito que esta issue já esteja finalizada? O que acha?
